<script>
    let schooName = "Shishu Vidya Niketan Nahan"
</script>
<section class="slide-in-left ">
    <div class="px-4 py-12 mx-auto max-w-7xl sm:px-6 md:px-12 lg:px-24 lg:py-24">
      <div class="text-center text-black">
        <h1 class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4">
          Welcome to {schooName}
        </h1>
  
        <p class="max-w-2xl mx-auto text-lg sm:text-xl md:text-2xl mb-8">
          Where education and excellence meet to shape the future.
        </p>
  
        <a href="/" class=" bg-indigo-600 py-2 px-4 text-base sm:text-lg font-semibold text-white hover:text-gray-200  rounded-full
    " >
          Explore Our Programs
        </a>
      </div>
    </div>
  </section>

  <style>
    .slide-in-left {
	-webkit-animation: slide-in-left 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        }
/* ----------------------------------------------
 * Generated by Animista on 2023-10-25 18:31:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}


  </style>
  